# .github/workflows/mergeUpstreamBranches.yml

name: sync::lazydocker::origin.yml

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 0 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'keneucker'
          git config --global user.email 'keneucker@gmail.com'
          # git config --global push.default 'current'

          # "git checkout production" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/jesseduffield/lazydocker.git
          git fetch upstream
          git checkout --track origin/master
          git checkout production
          git merge --no-edit upstream/master
          git push origin production
